"""Generate supabase/seeds/0005_seed_country_profiles.sql from the live World Bank
country registry.

Run occasionally to refresh the committed seed:

    python backend/scripts/generate_country_seed.py

Uses only the standard library so it runs without a configured environment. The
output SQL is deterministic (sorted by ISO-3 code) and idempotent (ON CONFLICT),
so re-running produces a clean diff.

IMF classification is DERIVED, not fetched: an economy is "Advanced" if it appears
in the IMF WEO Advanced Economies list below; otherwise it is "Emerging" or
"Developing" based on its World Bank income group. This is a documented heuristic,
never presented as authoritative IMF data.
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

WB_COUNTRY_URL = "https://api.worldbank.org/v2/country?format=json&per_page=400"

# IMF WEO "Advanced Economies" (ISO-3). Source: IMF World Economic Outlook groupings.
IMF_ADVANCED: frozenset[str] = frozenset(
    {
        "AND",
        "AUS",
        "AUT",
        "BEL",
        "CAN",
        "CHE",
        "CYP",
        "CZE",
        "DEU",
        "DNK",
        "ESP",
        "EST",
        "FIN",
        "FRA",
        "GBR",
        "GRC",
        "HKG",
        "IRL",
        "ISL",
        "ISR",
        "ITA",
        "JPN",
        "KOR",
        "LTU",
        "LUX",
        "LVA",
        "MAC",
        "MLT",
        "NLD",
        "NOR",
        "NZL",
        "PRI",
        "PRT",
        "SGP",
        "SMR",
        "SVK",
        "SVN",
        "SWE",
        "TWN",
        "USA",
    }
)

OUTPUT_PATH = (
    Path(__file__).resolve().parents[2] / "supabase" / "seeds" / "0005_seed_country_profiles.sql"
)


def derive_imf_classification(iso3: str, income: str) -> str:
    """Advanced from the IMF list; else Emerging/Developing by WB income group."""
    if iso3 in IMF_ADVANCED:
        return "Advanced"
    if income == "Low income":
        return "Developing"
    # High (non-advanced), Upper middle, Lower middle, or Not classified.
    return "Emerging"


def flag_emoji(iso2: str) -> str:
    """Two ISO-2 letters -> regional-indicator-symbol flag emoji (e.g. AW -> 🇦🇼)."""
    iso2 = iso2.strip().upper()
    if len(iso2) != 2 or not iso2.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + (ord(ch) - ord("A"))) for ch in iso2)


def sql_str(value: str | None) -> str:
    """Render a Postgres string literal (or NULL), escaping single quotes."""
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def fetch_countries() -> list[dict]:
    req = urllib.request.Request(WB_COUNTRY_URL, headers={"User-Agent": "EconRadar-seed/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    # World Bank returns [metadata, [rows]]. Aggregates carry region.id == "NA".
    rows = payload[1]
    countries = [r for r in rows if (r.get("region") or {}).get("id") not in (None, "", "NA")]
    countries.sort(key=lambda r: r["id"])
    return countries


def build_sql(countries: list[dict]) -> str:
    lines = [
        "-- ─────────────────────────────────────────────────────────────",
        "-- 0005_seed_country_profiles.sql — static country reference data",
        "-- GENERATED by backend/scripts/generate_country_seed.py — do not edit by hand.",
        "-- Source: World Bank country registry (names, ISO codes, region, income group).",
        "-- imf_classification is derived (see the generator's docstring).",
        f"-- {len(countries)} economies.",
        "-- ─────────────────────────────────────────────────────────────",
        "",
        "insert into country_profiles",
        "    (country_code, country_name, region, income_classification, imf_classification, flag_emoji)",
        "values",
    ]
    values = []
    for c in countries:
        iso3 = c["id"].strip()
        name = c["name"].strip()
        region = (c.get("region") or {}).get("value", "").strip()
        income = (c.get("incomeLevel") or {}).get("value", "").strip()
        income = "" if income in ("Aggregates", "Not classified") else income
        imf = derive_imf_classification(iso3, income)
        flag = flag_emoji(c.get("iso2Code", ""))
        values.append(
            f"    ({sql_str(iso3)}, {sql_str(name)}, {sql_str(region)}, "
            f"{sql_str(income)}, {sql_str(imf)}, {sql_str(flag)})"
        )
    lines.append(",\n".join(values))
    lines.append("on conflict (country_code) do update set")
    lines.append("    country_name          = excluded.country_name,")
    lines.append("    region                = excluded.region,")
    lines.append("    income_classification = excluded.income_classification,")
    lines.append("    imf_classification    = excluded.imf_classification,")
    lines.append("    flag_emoji            = excluded.flag_emoji,")
    lines.append("    updated_at            = now();")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    countries = fetch_countries()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(build_sql(countries), encoding="utf-8")
    print(f"Wrote {len(countries)} country profiles to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
